<h1>Top Ten Best Moments from The Book of Mormon</h1>
<p>I get chills every time I see The Book of Mormon. Itʼs so epic. Itʼs so enveloping.</p>
<p>The story chronicles sets of missionaries struggling to spread a message that isnʼt always very warmly received by the people who are so consumed in their own problems, they often refuse to listen.</p>
<p>Like every indignant book fan, I was disappointed by certain key omissions from the final script. So, to bring it full circle for you, Iʼve compiled a list of my ten favorite moments from the book that didnʼt make it into the show.</p>
<h2>10.</h2>
<h2>9.</h2>
<h2>8.</h2>
<h2>7.</h2>
<h2>6.</h2>
<h2>5.</h2>
<h2>4.</h2>
<h2>3.</h2>
<h2>2.</h2>
<h2>1.</h2>
<!-- Remember when you saw Harry Potter? The only thing those two things had in common was… -->