<section class="content_width">
	<header>
		<h1>Voicing the Keyboard</h1>
		<time datetime="2016-09-10">10 September 2016</time>
	</header>
	
	
	<p>When I auditioned for Mayfield Singers over a year ago, I saw that telling glimmer in their eye. I wish it had been for some gushingly dulcet vocal performance I gave. Alas, they saw a web designer and threw open the gates for my “talents”. I’ll now have to prove my worth in other ways, lest they toss me out now their website and logo are done.</p>
	
	<p>Truth be told, it has been a very gratifying project for me. Given how code-heavy my day job is, it’s been refreshing to limber up my joints on a project that’s proven more design-heavy.</p>
	
	<h2>The Logo</h2>
	
	<p><em>But Mayfield Singers already had a logo, Andy! Are you so arrogant to assume you could do it better?</em> No, that wasn’t the spirit in which this change was made. The beloved former logo served us very well for 2 years. But as we started to pivot toward a more aggressive publicity strategy, which involves a lot of social media activity, we realized that there were a few ways a new logo might fit those purposes better.</p>
	
	<p>I began with some rudimentary research. The meaning of the word Mayfield makes reference to a certain plant that grows a small white flower and has red roots used for making red dyes. That made for some good imagery for use in the logo. A lot of musical imagery was also considered, but as beautiful a glyph as the treble clef is, I could not resort to it. The cliché is unbearable to me.</p>
	
	<p>I happened to notice that the word Mayfield (in title case) is a beautifully symmetrical word. I wanted to work that into the logo, but it made the rest of the layout less harmonious.</p>
	
	<p>I followed up with a rather lengthy sketching phase. More than any other logo I've designed in the past, I was stuck in this phase for a long time, unable to find a direction I was happy with. I wore out my oven mits throwing it on and off the back-burner for a few months. </p>
	
	<p>The gist of it is, we need a logo system that is flexible and reconfigurable to work in a wider variety of circumstances. It needs to work with different background colors, alignments, sizes and orientations to meet the volatile digital world in which it performs. It has to work as a tiny social avatar on screen and then printed huge on an event poster!</p>
	
	<p>Given that the badge component can carry the brand independent of any typography, that makes it possible to separate the badge for social media use, and rearrange it more easily for different alignments.</p>
	
	
	
	<h2>The Website</h2>
	
	

</section>