<section class="content_width">
	<header>
		<h1>Voicing the Keyboard</h1>
		<time datetime="2016-09-10">10 September 2016</time>
	</header>
	
	
	<p>When I auditioned for Mayfield Singers over a year ago, I saw that telling glimmer in their eye. I wish it had been for some gushingly dulcet vocal performance I gave. Alas, they saw a web designer and threw open the gates for my “talents”. I’ll now have to prove my worth in other ways, lest they toss me out now their website and logo are done.</p>
	
	<p>Truth be told, it was a pretty gratifying project for me. Given how code-heavy my day job is, it’s been refreshing to limber up my joints on a project that’s proven more design-heavy.</p>
	
	<h2>The Logo</h2>
	
	<p><em>But Mayfield Singers already had a logo, Andy! Are you so arrogant to assume you could do it better?</em> No, that wasn’t the spirit in which this change was made. The beloved former logo served us very well for 2 years. But as we started to pivot toward a more aggressive publicity strategy, which involves a lot of social media activity, we realized that there were a few ways a new logo might fit those purposes better.</p>
	
	<p>The gist of it is, we need a logo system that is flexible and reconfigurable to work in a wider variety of circumstances. It needs to work with different background colors, alignments, sizes and orientations to meet the volatile digital world in which it performs. Can we shrink it down to a tiny social avatar and then blow it up huge on an event poster?</p>
	
	<p>Crucial to meeting these requirements is the badge. The badge component is able to carry the brand independent of the typography — which is what makes it successful as a standalone social media avatar. As I researched </p>
	
	<h2>The Website</h2>
	
	

</section>