<link rel="stylesheet" href="/articles/voicing-the-keyboard/article_style.css" />
<title>Voicing the Keyboard</title>
<meta name="description" content="The brand new Mayfield Singers website and branding, and how they were made." />
<meta name="keywords" content="website, logo, design, choir, mayfield, singers" />
<meta property="og:image" content="http://blog.andygriff.in/articles/voicing-the-keyboard/imgs/article_og.jpg">