<link rel="stylesheet" href="/articles/voicing-the-keyboard/article_style.css" />
<title>Voicing the Keyboard</title>
<meta name="description" content="I fell in love with neon signs and had a blank space on the wall. So I made one. This is how." />
<meta name="keywords" content="neon, DIY, woodworking, art deco, light" />
<meta property="og:image" content="http://blog.andygriff.in/articles/because-neon/imgs/article_og.jpg">