<section class="content_width">
	<header>
		<h1>Happy Place: A Pixar Cityscape</h1>
		<time datetime="2015-02-19">19 February 2015</time>
	</header>
	
	<p>For any given free form design assignment like this one, I always come up with at least one Pixar-themed idea. Iʼm a hopeless groupie. But the idea of an architectural homage to Pixar films was just too compelling to ignore.</p>
	<p>It went from a complex and vast cityscape filled with every piece of Pixar architecture I could think of, to a single row of buildings made from just one edifice from each film. Crisis averted. But I wanted to keep the element of discovery it had, and I was afraid Iʼd lose that in the simplification.</p>
</section>
<figure class="happy_place_full full_bleed"></figure>
<section class="content_width">
	<p>My next pass left me with a black &amp; white, lines-only illustration arranged in a centered, triangular composition. But Iʼd done exactly as I feared; I created a design that was glanceable, not discoverable. In black &amp; white, it lacked depth, and became texture. And the symmetrical, triangular composition was a pleasing shape, but it was too easy to accept the piece as one shape and move on after a glance. Additionally it put one building at the focal point of the piece which created a sense of favoritism.</p>
	<p>So, I added a dash of color to the sky which immediately helped to distinguish the buildings, and force depth. Then I broke the composition into three groups of buildings to do away with the single focal point, and encourage more exploration of the scene.</p>
	<p>To pick up a print of your own, head over to my <a href="http://www.redbubble.com/people/gandrewb/works/14061212-happy-place-a-pixar-cityscape">Redbubble store</a>. This design was also the subject of my <a href="https://dribbble.com/shots/1938995-Happy-Place-A-Pixar-Cityscape">inaugural Dribbble shot</a>, and my <a href="https://twitter.com/andybgriffin/status/568448357015777280">1000<sup>th</sup> tweet</a>!</p>
</section>