<section class="content_width">
	<header>
		<h1>Happy Place: A Pixar Cityscape</h1>
		<time datetime="2015-02-17">17 February 2015</time>
	</header>
	
	<p>In any given free form design assignment like this one, there will inevitably be a Pixar-themed idea somewhere on my list. Iʼm an incurable groupie. But the idea of an architectural homage to Pixar films was just too compelling to ignore.</p>
	<p>I moved from a complex and vast cityscape filled with every piece of Pixar architecture I could think of, to a single row of buildings comprised of just one edifice from each film. Crisis averted. I did want to maintain the element of discovery, however and I was afraid Iʼd lose that in the simplification.</p>
</section>
<figure class="happy_place_full full_bleed"></figure>
<section class="content_width">
	<p>My next pass left me with a black &amp; white, lines-only illustration arranged in a centered, triangular composition. But Iʼd done exactly as I feared; I created a design that was glanceable, not discoverable. In black &amp; white, it lacked depth, and became texture. And the symmetrical, triangular composition was a pleasing shape, but it made it too easy to accept the piece as one shape and move on after a glance. Additionally it put one building at the focal point of the piece which would have implied some kind of favoritism.</p>
	<p>So, I added a dash of color to the sky which immediately helped to distinguish the buildings, and force depth. Then I chose the composition featuring three groups of buildings (which was my favorite anyway) to do away with the single focal point, and encourage more exploration of the scene.</p>
	<p>To pick up a print of your own, head over to my <a href="#">Zazzle store</a>. This design was also the subject of my <a href="#">inaugural Dribbble shot</a>, and my <a href="#">1000<sup>th</sup> tweet</a>!</p>
</section>