<section class="content_width">
	<header>
		<h1>Itʼs Earth Day, Hippies!</h1>
		<time datetime="2015-04-27">27 April 2015</time>
	</header>
	
	<p>If you did an inventory of my political leanings, youʼd find that they align best with the Conservative philosophy. But please donʼt call me a Republican. I donʼt like that word anymore.
	</p>
	<p>I first felt to address this subject under a broader, “I Agree with Conservatives Except on the Following Points” article. Thatʼs still forth‑coming. But Iʼve devoted the last several weeks of my life to an environmental project at work which culminated in an inspiring, celebratory Earth Day. It expanded — and it engulfed me. This stuff is important.</p>
	<p>I use the word celebratory to describe my Earth Day experience because it was. A rock concert, a product launch. Free beverages all around! But more than that, it was a moving and even spiritual experience for me. I was infused with gratitude for our little planet and its Creator.</p>
	<p>It is after a unifying experience like this, that I canʼt make sense of the partisanship. Living on our Earth together may be the very last thing we have in common, but then we canʼt agree on how to, or even whether to take care of it. A new idea is proposed and the knee‑jerk reaction of anyone in the other party is to diverge for the sake of divergence. Heaven forbid we should ever agree on something!</p>
	<p>So, letʼs blame this on Al Gore. Heʼs a Democrat. He had the tallest podium when we all needed to start paying attention. And as a Conservative, I never cared much for him. Iʼd heard all the sound bites. But I heard him speak on Earth Day, and what I heard was a man who cares deeply about a cause that I also care about. He has devoted a great many years of his life to protecting our planet. I gained a lot of respect for him. This isnʼt a political problem, itʼs a human problem.</p>
	
	<h2>Consider the following:</h2>
	
	<p>Because solar energy and other renewables are rooted in technology instead of finite resources, the cost will only continue to decrease as the science improves. By many accounts, solar energy is already saving money.</p>
	<p>The solar energy absorbed by the Earth in one hour could meet the energy needs of humanity for <a href="http://en.wikipedia.org/wiki/Solar_energy#Energy_from_the_Sun">more than a year</a>. There are 8760 hours in a year &mdash; a bit of untapped potential there, Iʼd say.</p>
	<p>Like children scrambling for piñata entrails, we fight over finite supplies of fossil fuels. It only gets worse as the supply diminishes. Renewable energy domesticates all power generation which allows us to break free from corrupt foreign oil tycoons and the conflicts we inevitably have with them.</p>
	<p>The volatility of our economy has so much to do with the cost of a barrel of gas. It fluctuates based on the amount we think we have, or the amount the Middle East is willing to sell to us. Imagine the stability our economy would gain by eliminating that variable from the equation.</p>
	
	<blockquote>
		<p>Thou shalt be diligent in preserving what thou hast, that thou mayest be a wise steward; for it is the free gift of the Lord thy God, and thou art his steward.</p>
		<cite><a href="https://www.lds.org/scriptures/dc-testament/dc/136.27?lang=eng#26">Doctrine and Covenants 136:27</a></cite>
	</blockquote>
	
	<h2>A Moment With My Fellow Friends of Faith:</h2>
	
	<p>I find it very regrettable that we, as Christians, are often portrayed as the enemies of efforts to take care of our planet. Instead, we should be leading the charge! I believe that Earth has the capacity to support every human life God chooses to send to it, and that He offered Earth as a gift to humanity to support His higher purposes for us. But as weʼre taught in Matthew from the <a href="https://www.lds.org/scriptures/nt/matt/25.14-30?lang=eng#19">Parable of the Talents</a>, the abundance is only given to those who take care of their gifts. It is those who do not that are left wanting.</p>
	
	

</section>